name: "go-run-schedule"

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  go-run-schedule:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Setup Git Project"
        uses: "actions/checkout@v3"

      - name: "Setup Go Env"
        uses: "actions/setup-go@v3"
        with:
          cache: true
          go-version: "1.19.2"

      - name: "Update Prices CSV"
        env: 
          AWS_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY }}"
          AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
          AWS_REGION: "us-east-1"
        run: |
          go run main.go
